esphome:
  name: volume-control
  friendly_name: volume_control

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sIGDzgrcxV8GsZJCF/r298O31ob/toCsVzL4G4OZmWw="

ota:
  - platform: esphome
    password: "73c3f5b07adf7c1f5883309a2692c7f0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Volume-Control Fallback Hotspot"
    password: "RU96wQqwFh0z"

captive_portal:
    