esphome:
  name: volume_control
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

spi:
  clk_pin: 14
  mosi_pin: 13

display:
  - platform: st7789v
    model: "ROUND_240X240"
    cs_pin: 
    dc_pin: 15
    reset_pin: 12
    backlight_pin: 2
    rotation: 0
    lambda: |-
      it.print(120, 120, id(font1), TextAlign::CENTER, "Hello World");

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 32
